name: Main
on: [push, pull_request]
jobs:
  test-main:
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    strategy:
      matrix:
        libslirp_commit: [master, v4.3.1, v4.2.0, v4.1.0]
        ubuntu_version: ['18.04']
        include:
          - libslirp_commit: v4.3.1
            ubuntu_version: '20.04'
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t slirp4netns-tests --build-arg LIBSLIRP_COMMIT --build-arg UBUNTU_VERSION -f Dockerfile.tests .
      env:
        LIBSLIRP_COMMIT: ${{ matrix.libslirp_commit }}
        UBUNTU_VERSION: ${{ matrix.ubuntu_version }}
    - run: docker run --rm --privileged slirp4netns-tests
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: DOCKER_BUILDKIT=1 docker build -f Dockerfile.buildtests .
  artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: DOCKER_BUILDKIT=1 docker build -o /tmp/artifact -f Dockerfile.artifact .
    - run: (cd /tmp/artifact; mv slirp4netns slirp4netns-x86_64)
    - run: (cd /tmp/artifact; sha256sum *)
    - uses: actions/upload-artifact@v1
      with:
        name: slirp4netns-x86_64
        path: /tmp/artifact/slirp4netns-x86_64
